In [1]:
import pandas as pd
import numpy as np
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import cross_validate, StratifiedKFold
from sklearn.svm import SVC

In [2]:
x = pd.read_csv("data/X.csv", sep=' ', header=None, dtype=float)
X=x.values

In [3]:
y = pd.read_csv("data/y_bush_vs_others.csv", sep=' ', header=None)
y_bush = y.values.ravel()
y = pd.read_csv("data/y_williams_vs_others.csv", sep=' ', header=None)
y_williams = y.values.ravel()

In [4]:
X.shape

(13233, 4096)

In [5]:
np.sum(y_bush)

530

In [6]:
np.sum(y_williams)

52

In [7]:
y_bush.shape

(13233,)

In [8]:
# #PCA
# from sklearn.decomposition import PCA

# pca = PCA(n_components=2)
# pca.fit(X)
# print(pca.explained_variance_ratio_)
# print(pca.singular_values_)

In [9]:
#For Bush knn

from sklearn.decomposition import PCA
pca = PCA(n_components=64)
x_pca = pca.fit_transform(X)

#neighbors = [1,3,5]
neighbors = [1]
fit_time_bush = np.zeros((3,1))
score_time_bush = np.zeros((3,1))
test_f1_bush = np.zeros((3,1))
test_precision_bush = np.zeros((3,1))
test_recall_bush = np.zeros((3,1))
j = 0

for currentNeighbors in neighbors:
    #print (currentNeighbors)
    knn = KNeighborsClassifier(n_neighbors=currentNeighbors)
    knn_cv_result = cross_validate(knn, x_pca, y_bush, cv = StratifiedKFold(n_splits = 3, shuffle = True, random_state = 6925), 
                                    scoring=('precision', 'recall', 'f1'), return_train_score = False, n_jobs = -1)
    print("j", j, "currentNeighbor", currentNeighbors)
    #print(knn_cv_result)
    fit_time_bush[j][0] = np.mean(knn_cv_result['fit_time'])
    score_time_bush[j][0] = np.mean(knn_cv_result['score_time'])
    test_f1_bush[j][0] = np.mean(knn_cv_result['test_f1'])
    test_precision_bush[j][0] = np.mean(knn_cv_result['test_precision'])
    test_recall_bush[j][0] = np.mean(knn_cv_result['test_recall'])
    
    j = j+1

print("test_f1_bush", test_f1_bush)
print(knn_cv_result['test_f1'])
print("knn_cv_result", knn_cv_result)   

j 0 currentNeighbor 1
test_f1_bush [[0.1625208]
 [0.       ]
 [0.       ]]
[0.13670886 0.19047619 0.16037736]
knn_cv_result {'fit_time': array([0.05345368, 0.06244802, 0.04801178]), 'score_time': array([17.65689874, 17.86530066, 17.31608248]), 'test_precision': array([0.12385321, 0.20125786, 0.13709677]), 'test_recall': array([0.15254237, 0.18079096, 0.19318182]), 'test_f1': array([0.13670886, 0.19047619, 0.16037736])}


In [10]:
#For Williams knn
from sklearn.decomposition import PCA
pca = PCA(n_components=170)
x_pca_williams = pca.fit_transform(X)

neighbors = [1]
fit_time_williams = np.zeros((3,1))
score_time_williams = np.zeros((3,1))
test_f1_williams = np.zeros((3,1))
test_precision_williams = np.zeros((3,1))
test_recall_williams = np.zeros((3,1))
j = 0

for currentNeighbors in neighbors:
    #print (currentNeighbors)
    knn = KNeighborsClassifier(n_neighbors=currentNeighbors)
    knn_cv_result_williams = cross_validate(knn, x_pca_williams, y_williams, cv = StratifiedKFold(n_splits = 3, shuffle = True, random_state = 6925), 
                                    scoring=('precision', 'recall', 'f1'), return_train_score = False, n_jobs = -1)
    print("j", j, "currentNeighbor", currentNeighbors)
    print(knn_cv_result_williams)
    fit_time_williams[j][0] = np.mean(knn_cv_result_williams['fit_time'])
    score_time_williams[j][0] = np.mean(knn_cv_result_williams['score_time'])
    test_f1_williams[j][0] = np.mean(knn_cv_result_williams['test_f1'])
    test_precision_williams[j][0] = np.mean(knn_cv_result_williams['test_precision'])
    test_recall_williams[j][0] = np.mean(knn_cv_result_williams['test_recall'])
    j = j+1

print(knn_cv_result_williams['test_f1'])
print("mean: ", test_f1_williams)   

j 0 currentNeighbor 1
{'fit_time': array([0.12101722, 0.15621257, 0.16904378]), 'score_time': array([42.4363997 , 42.20268273, 42.31350279]), 'test_precision': array([0.71428571, 0.2       , 0.83333333]), 'test_recall': array([0.27777778, 0.11764706, 0.29411765]), 'test_f1': array([0.4       , 0.14814815, 0.43478261])}
[0.4        0.14814815 0.43478261]
mean:  [[0.32764359]
 [0.        ]
 [0.        ]]


In [11]:
print(knn_cv_result_williams['test_f1'])
print("mean: ", test_f1_williams)   

[0.4        0.14814815 0.43478261]
mean:  [[0.32764359]
 [0.        ]
 [0.        ]]


In [12]:
#SVC for Bush
from sklearn.decomposition import PCA
pca = PCA(n_components=3000, random_state = 6925)
x_pca_svc_bush = pca.fit_transform(X)


#C 1000 gamma 0.001,0.01,0.1
svc_fit_time_bush = np.zeros((1,1))
svc_score_time_bush = np.zeros((1,1))
svc_test_f1_bush = np.zeros((1,1))
svc_test_precision_bush = np.zeros((1,1))
svc_test_recall_bush = np.zeros((1,1))
j = 0

svc = SVC(C = 1000, kernel = 'poly', degree = 15,gamma = 0.001,  coef0 = 200)
#svc = SVC(C = 1000000, kernel = 'linear')
svc_cv_result = cross_validate(svc, x_pca_svc_bush, y_bush, cv = StratifiedKFold(n_splits = 3, shuffle = True, random_state = 6925), 
                           scoring=('precision', 'recall', 'f1'), return_train_score = False, n_jobs = -1)
svc_fit_time_bush[j][0] = np.mean(svc_cv_result['fit_time'])
svc_score_time_bush[j][0] = np.mean(svc_cv_result['score_time'])
svc_test_f1_bush[j][0] = np.mean(svc_cv_result['test_f1'])
svc_test_precision_bush[j][0] = np.mean(svc_cv_result['test_precision'])
svc_test_recall_bush[j][0] = np.mean(svc_cv_result['test_recall'])
    
print(svc_test_f1_bush)
print(svc_cv_result)


[[0.63492469]]
{'fit_time': array([50.70814633, 53.26008153, 52.76480365]), 'score_time': array([55.5096271 , 56.740201  , 56.44410992]), 'test_precision': array([0.66666667, 0.75362319, 0.66666667]), 'test_recall': array([0.56497175, 0.58757062, 0.60227273]), 'test_f1': array([0.6116208 , 0.66031746, 0.63283582])}


In [13]:
## SVC for Williams
from sklearn.decomposition import PCA
pca = PCA(n_components=2250, random_state = 6925)
x_pca_svc_williams = pca.fit_transform(X)

#C 1000 gamma 0.001,0.01,0.1
svc_fit_time_williams = np.zeros((3,1))
svc_score_time_williams = np.zeros((3,1))
svc_test_f1_williams = np.zeros((3,1))
svc_test_precision_williams = np.zeros((3,1))
svc_test_recall_williams = np.zeros((3,1))
j = 0
svc_test_f1_williams[0][0] = 0

svc = SVC(C = 1, kernel = 'sigmoid', gamma = 0.000244141)
#svc = SVC(C = 100, kernel = 'linear', degree = 2, gamma = 0.001)
svc = SVC(C = 1000, kernel = 'poly', degree = 15,gamma = 0.001,  coef0 = 200)
svc_cv_result_williams = cross_validate(svc, x_pca_svc_williams, y_williams, cv = StratifiedKFold(n_splits = 3, shuffle = True, random_state = 6925), 
                           scoring=('precision', 'recall', 'f1'), return_train_score = False, n_jobs = -1)
svc_fit_time_williams[j][0] = np.mean(svc_cv_result_williams['fit_time'])
svc_score_time_williams[j][0] = np.mean(svc_cv_result_williams['score_time'])
svc_test_f1_williams[j][0] = np.mean(svc_cv_result_williams['test_f1'])
svc_test_precision_williams[j][0] = np.mean(svc_cv_result_williams['test_precision'])
svc_test_recall_williams[j][0] = np.mean(svc_cv_result_williams['test_recall'])
    
print(svc_test_f1_williams)
print(svc_cv_result_williams)


[[0.51594203]
 [0.        ]
 [0.        ]]
{'fit_time': array([8.06819105, 7.42490959, 8.09371829]), 'score_time': array([8.83571124, 8.32851028, 8.86786437]), 'test_precision': array([0.75      , 0.66666667, 0.69230769]), 'test_recall': array([0.5       , 0.23529412, 0.52941176]), 'test_f1': array([0.6       , 0.34782609, 0.6       ])}


In [14]:
import pickle

# print("test_f1_bush: ", test_f1_bush)
# print("test_f1_williams: ", test_f1_williams)
# print("svc_test_f1_bush: ", svc_test_f1_bush[0][0])
# print("svc_test_f1_williams: ", svc_test_f1_williams[0][0])


# Once you run the code, it will generate a 'results.pkl' file. Do not modify the following code.
#bush.pkl
# test_f1_bush = np.zeros((3,1))
# svc_test_f1_bush = np.zeros((3,1))
# test_f1_williams = np.zeros((3,1))
# svc_test_f1_williams = np.zeros((3,1))

# test_f1_bush[0][0] = 0.14676116
# test_f1_bush[1][0] = 0.07976078
# test_f1_bush[2][0] = 0.039048693
# svc_test_f1_bush[0][0] = 0.626287073

bush = list()
bush.append(test_f1_bush[0][0])
# bush.append(test_f1_bush[1][0])
# bush.append(test_f1_bush[2][0])
bush.append(svc_test_f1_bush[0][0])

pickle.dump((bush), open('bush.pkl', 'wb'))

#williams.pkl
# test_f1_williams[0][0] = 0.230716143
# test_f1_williams[1][0] = 0.0
# test_f1_williams[2][0] = 0.0
# svc_test_f1_williams[0][0] = 0.482608697

williams = list()
williams.append(test_f1_williams[0][0])
# williams.append(test_f1_williams[1][0])
# williams.append(test_f1_williams[2][0])
williams.append(svc_test_f1_williams[0][0])

pickle.dump((williams), open('williams.pkl', 'wb'))


In [15]:
xs = pickle.load(open('bush.pkl', 'rb'))
print(xs)

xs = pickle.load(open('williams.pkl', 'rb'))
print(xs)

[0.1625208032420834, 0.6349246921066721]
[0.3276435856146001, 0.5159420289855072]
